//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_id { get; set; }
        public string Product_code { get; set; }
        public string Product_name { get; set; }
        public int Category_id { get; set; }
        public double Product_price { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
